---
deployment:
  tasks:
    - export DEPLOYPATH=/home/martiniv/repositories/mvesto/public_html
    - /mvesto index.html $DEPLOYPATH
    - /mvesto style.css $DEPLOYPATH
    - /mvesto -R assets $DEPLOYPATH
