---
deployment:
  tasks:
    - export DEPLOYPATH=/home/martiniv/repositories/mvesto/public.html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
